### ISSUE TITLE
Can't seem to *not* require minitest/ci

### ISSUE THREAD

**Issue by chrisnicola** [bhenderson/minitest-ci#17]
I have this in my `Gemfile`:

```
group :test do
    gem 'minitest-ci', require: false
end
```

And this in my `test_helper.rb`

```
if ENV["CI"]
  require 'minitest/ci'
else
  require 'pry'
end
```

However this doesn't seem to work, it always seems to require `minitest/ci` and generates the ci files, even when `ENV["CI"]` is not set and `require 'minitest/ci'` is never called. The only way to prevent it is to remove it from the Gemfile.

Anyone have any ideas?

**Comment by bhenderson** [comment]
hi @chrisnicola, interesting issue.

Minitest auto loads all it's plugins by looking for `minitest/*_plugin.rb`. I tried looking around in minitest's source, but I couldn't find a good solution. This hack _might_ work

``` ruby
# require "minitest/ci_plugin"
Gem.find_files("minitest/ci_plugin.rb").each{|f| require f} # yuck!
def Minitest.plugin_ci_init(*a) end
```

Pretty interesting, plugins get loaded at run time, and it uses the full path, making it difficult to override.

But I don't maintain this anymore, checkout https://github.com/circleci/minitest-ci see if they have anything.

Out of curiosity, why do you want to disable it sometimes? is it slow?

**Comment by chrisnicola** [comment]
I don't know if it is slow, but I only need it on the CI server so it seemed a bit silly to generate a bunch of XML output I wasn't using.

I keep having more and more issues doing basic things with MiniTest lately.
